version: '3.8'

services:
  spotbugs:
    build:
      context: .
      dockerfile: spot/Dockerfile
    container_name: spotbugs
    volumes:
      - ./input:/app/input


  bandit:
    build:
      context: .
      dockerfile: bandit/Dockerfile
    container_name: bandit
    volumes:
      - ./input:/app/input

  cppcheck:
    build:
      context: .
      dockerfile: cppcheck/Dockerfile
    container_name: cppcheck
    volumes:
      - ./input:/app/input

  semgrep:
    build:
      context: .
      dockerfile: semgrep/Dockerfile
    container_name: semgrep
    volumes:
      - ./input:/app/input

  devskim:
    build: 
      context: .
      dockerfile: devskim/Dockerfile
    container_name: devskim
    volumes:
      - ./input:/app/input
  
volumes:
  shared-data: