version: '3.8'

services:
  spotbugs:
    build:
      context: .
      dockerfile: spot/Dockerfile
    container_name: spot_container
    ports:
      - "5000:5000"
    volumes:
      - shared-data:/shared

  java_app:
    build:
      context: .
      dockerfile: analyzer/Dockerfile
    depends_on:
      - spotbugs
    container_name: analyzer_container
    volumes:
      - shared-data:/shared

  frama-c:
    build: 
      context: .
      dockerfile: frama-c/Dockerfile
    container_name: frama-c
    volumes:
      - ./input:/app/input

volumes:
  shared-data: