version: '3.8'

services:
  semgrep:
    image: semgrep-analyzer:latest
    container_name: semgrep-analyzer
    entrypoint: ""
    command: ["sh", "-c", "semgrep scan --config auto /input/$TARGET_FILE | tee /output/semgrep_result.txt"]
    volumes:
      - ./input:/input
      - ./output:/output
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

  cppcheck:
    image: cppcheck-analyzer:latest
    container_name: cppcheck-analyzer
    entrypoint: ""
    command: ["sh", "-c", "cppcheck --enable=all --xml /input/$TARGET_FILE 2>&1 | tee /output/cppcheck_result.txt"]
    volumes:
      - ./input:/input
      - ./output:/output
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

  bandit:
    image: bandit-analyzer:latest
    container_name: bandit-analyzer
    entrypoint: ""
    command: ["sh", "-c", "bandit -r /input/$TARGET_FILE -f txt | tee /output/bandit_results.txt"]
    volumes:
      - ./input:/input
      - ./output:/output
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

  devskim:
    image: devskim-analyzer:latest
    container_name: devskim-analyzer
    entrypoint: ""
    command: ["sh", "-c", "devskim analyze --source-code /input/$TARGET_FILE --output-format text | tee /output/devskim_results.txt"]
    volumes:
      - ./input:/input:rw
      - ./output:/output:rw
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

