# # Base image
# FROM python:3.11

# # Install Semgrep
# RUN pip install semgrep

# # Set the working directory
# WORKDIR /src

# # Copy the code and rules into the container
# COPY . /src

# # Ensure that Semgrep runs with correct paths and saves output to JSON
# CMD ["semgrep", "--config=/src/buffer_overflow_rules.yml", "/src/test_code.cpp", "--json", "--output=/src/semgrep_report.json"]

# Base image
FROM python:3.11

# Install Semgrep
RUN pip install semgrep

# Set the working directory
WORKDIR /workspace

# Copy the code and rules into the container
COPY . /workspace

# Ensure that Semgrep runs with all available rules and saves output to TXT format
ENTRYPOINT [""]

